### PR TITLE
Updated ID's to conllu format

### PR DESCRIPTION
**Pull request by stavkl**
I changed the IDs to match the conllu formatting. I tested the change locally on the files under the resources directory

### CODE REVIEW

**Comment by epageperron** [comment]
Thanks! Does this also take into account updating the head column?

**Comment by stavkl** [comment]
No, from what I understood that the syntactic parsing will be done according to the new ID's. Right now the HEAD is not specified for all the tokens

**Comment by epageperron** [comment]
Okay, we'll have to add that once the converter to conll-u to cdli-conll is
written. Thanks!

**Comment by epageperron** [comment]
hey Stav! So I tried it but it keeps the current IDs, I think I'm not updating the code properly. I fetched your branch and run the install from it but it looks like it's still using the previous version. Is there a way for me to test only converter.py? When I try pthon3 converter.py -i my_file nothing happens.  Basically giving me the steps to test would help a lot :)

**Comment by stavkl** [comment]
Hi, I tested the changes in the python console - just imported directly the `CdliCoNLLtoCoNLLUConverter` module and ran `test = CdliCoNLLtoCoNLLUConverter('./resources/P100149.conll', './resources/test_res', False) -->
test.convert() -->
test.writeToFile()`, which is essentialy what happens in the `file_process` function in the cli.py module.
I'm guessing it's not showing any changes on your end because you have the package already installed? I didn't install it beforehand

**Pull request merged**
